# Don't print a new line at the start of the prompt
add_newline = false

prompt_order = [
  "username",
  "hostname",
  "directory",
  "git_branch",
  "git_state",
  "git_status",
  "golang",
  "kubernetes",
  "nix_shell",
  "aws",
  "cmd_duration",
  "jobs",
  "battery",
  "line_break",
  "time",
  "character",
]

[character]
symbol = "➜"
error_symbol = "✖"
use_symbol_for_status = true

[directory]
style = "bold blue"

[git_state]
progress_divider = " of "

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[time]
format = "%H:%M:%S"
style = "bold dimmed black"
disabled = false

[username]
disabled = false
show_always = true
style_root = "bold red"
style_user = "bold green"
