# Don't print a new line at the start of the prompt
add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $cmd_duration\
  $custom\
  $line_break\
  $jobs\
  $battery\
  $time\
  $character\
  """

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "

[java]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[time]
time_format = "%H:%M:%S"
style = "bold dimmed black"
format = "[$time]($style) "
disabled = false

[username]
show_always = true
style_user = "bold green"